name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get python version
        id: python-version
        run: echo "::set-output name=version::$(cat .python-version)"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.version }}
      - name: Build
        run: python cli.py build
      - name: Prepare release
        id: prepare-release
        run: |
          echo "::set-env name=RELEASE_VERSION::$(date +""%d-%m-%Y-%H-%M"")"
          echo "::set-env name=DICTIONARY_SIZE::$(cat dictionary.txt | wc -l)"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "rev ${{ env.RELEASE_VERSION }}"
          tag_name: ${{ format('rev_{0}', env.RELEASE_VERSION ) }}
          files: |
            dictionary.txt
          body: |
            Release metadata
            - ${{ env.DICTIONARY_SIZE }} words in dictionary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

