name: CICD
on: [push]
  #  push:
    #    branches:
    #      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get python version
        id: python-version
        run: echo "::set-output name=version::$(cat .python-version)"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.version }}
      - name: Build
        run: python cli.py build
      - name: Prepare release
        id: prepare-release
        run: |
          echo "::set-output name=release-version::$(date +\"%d-%m-%Y-%T\")"
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.prepare-release.release-version }}
          tag_name: ${{ steps.prepare-release.release-version }}
