name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get python version
        id: python-version
        run: echo "::set-output name=version::$(cat .python-version)"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.version }}
      - name: Build
        run: python src/build.py
      - name: Prepare release
        id: prepare-release
        run: |
          echo "RELEASE_VERSION=$(date +""%d-%m-%Y-%H-%M"")" >> $GITHUB_ENV
          echo "FULL_DICTIONARY_SIZE=$(cat dictionary_full.txt | wc -l)" >> $GITHUB_ENV
          echo "COMMON_DICTIONARY_SIZE=$(cat dictionary_common.txt | wc -l)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "rev ${{ env.RELEASE_VERSION }}"
          tag_name: ${{ format('rev_{0}', env.RELEASE_VERSION ) }}
          files: |
            dictionary_full.txt
            dictionary_common.txt
          body: |
            Release metadata
            - ${{ env.FULL_DICTIONARY_SIZE }} words in full dictionary
            - ${{ env.COMMON_DICTIONARY_SIZE }} words in common words dictionary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
